# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\add.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add(object):
    def setupUi(self, add):
        add.setObjectName("add")
        add.resize(602, 328)
        add.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"")
        self.centralwidget = QtWidgets.QWidget(add)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 511, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 200, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 270, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 130, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(260, 130, 211, 31))
        self.lineEdit.setObjectName("lineEdit")
        add.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(add)
        self.statusbar.setObjectName("statusbar")
        add.setStatusBar(self.statusbar)

        self.retranslateUi(add)
        QtCore.QMetaObject.connectSlotsByName(add)

    def retranslateUi(self, add):
        _translate = QtCore.QCoreApplication.translate
        add.setWindowTitle(_translate("add", "MainWindow"))
        self.label.setText(_translate("add", "Add a New Book to Library"))
        self.pushButton.setText(_translate("add", "Add Book"))
        self.pushButton_2.setText(_translate("add", "Back"))
        self.label_2.setText(_translate("add", "Book No: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add = QtWidgets.QMainWindow()
    ui = Ui_add()
    ui.setupUi(add)
    add.show()
    sys.exit(app.exec_())
